#ft_transcendence

services:
  website:
    pull_policy: build
    build:
      context:
      args:
        - NODE_VERSION=${NODE_VERSION}
    image : ${WEBSITE_SERVICE_IMAGE}
    container_name: pong-${WEBSITE_SERVICE}
    ports: "3001:3001"
    environment:
      - NODE_ENV=${DEV_ENV}
    
  monitoring:
    image: ${MONITORING_SERVICE_IMAGE}
    container_name: pong-${MONITORING_SERVICE}
    ports:
      - "9090:9090"
    volumes:
      - monitoring-logs:/prometheus
    configs:
      - source: prometheus-config
        target: /etc/prometheus/prometheus.yml
  
  monitoring-visualiser:
    image: ${MONITORING_VISUALISER_SERVICE_IMAGE}
    container_name: pong-${MONITORING_VISUALISER_SERVICE}
    ports:
      - "3000:3000"


networks:
  pong:

volumes:
  monitoring-logs:
    name: pong-${MONITORING_SERVICE}

configs:
  prometheus-config:
    file: ${SRCS_MONITORING_CONFIG}