#Trong, the project

services:
  website:
    build:
      context: .
      dockerfile: services/${WEBSITE_SERVICE}/Dockerfile
      args:
        - NODE_VERSION=${NODE_VERSION}
    image: ${WEBSITE_SERVICE_IMAGE}
    container_name: pong-${WEBSITE_SERVICE}
    hostname: Trong
    ports:
      - "${PORT}:${PORT}"
    environment:
      - NODE_ENV=${DEV_ENV}
    volumes:
      - db:/home/db
    secrets:
      - SSL-certificate
      - SSL-key
      - JWT-secret
    networks:
      - pong

networks:
  pong:

volumes:
  db:
    name: ${DB_SERVICE}

secrets:
  SSL-certificate:
    file: ${SECRETS}${SSL_CERTIFICATE}
  SSL-key:
    file: ${SECRETS}${SSL_KEY}
  JWT-secret:
    file: ${SECRETS}JWT-secret